/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/healthz": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health check */
        get: operations["healthCheck"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/register": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create account, return access + refresh tokens */
        post: operations["register"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Validate credentials, return tokens */
        post: operations["login"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/refresh": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Exchange refresh token for new access token */
        post: operations["refreshToken"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Revoke refresh token */
        post: operations["logout"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Return current user */
        get: operations["getMe"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/gyms": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List gyms user belongs to */
        get: operations["listGyms"];
        put?: never;
        /** Create gym (admin only) */
        post: operations["createGym"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/gyms/{gymSlug}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get gym details (member) */
        get: operations["getGym"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/gyms/{gymSlug}/members": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Invite user by email (admin) */
        post: operations["inviteMember"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/gyms/{gymSlug}/walls": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List walls (member) */
        get: operations["listWalls"];
        put?: never;
        /** Create wall (setter+) */
        post: operations["createWall"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/gyms/{gymSlug}/walls/{wallId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get wall detail + active image + job status (member) */
        get: operations["getWall"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/gyms/{gymSlug}/walls/{wallId}/images": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Upload wall photo (setter+, multipart) */
        post: operations["uploadWallImage"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/gyms/{gymSlug}/walls/{wallId}/holds": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Return holds for active wall image (member) */
        get: operations["listHolds"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/gyms/{gymSlug}/walls/{wallId}/routes": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List routes with send counts (member) */
        get: operations["listRoutes"];
        put?: never;
        /** Create route (member) */
        post: operations["createRoute"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/gyms/{gymSlug}/walls/{wallId}/routes/{routeId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get route detail (member) */
        get: operations["getRoute"];
        put?: never;
        post?: never;
        /** Delete route (creator or setter) */
        delete: operations["deleteRoute"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/gyms/{gymSlug}/walls/{wallId}/routes/{routeId}/sends": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Log a send (member) */
        post: operations["logSend"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/gyms/{gymSlug}/walls/{wallId}/routes/{routeId}/sends/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Remove send (member) */
        delete: operations["removeMySend"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/users/me/logbook": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** All sends by current user */
        get: operations["getMyLogbook"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/gyms/{gymSlug}/invites": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Generate invite token (admin) */
        post: operations["createInvite"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/invites/{token}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Validate invite (no auth) */
        get: operations["validateInvite"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/invites/{token}/accept": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Accept invite (authenticated) */
        post: operations["acceptInvite"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        Error: {
            error: string;
        };
        User: {
            /** Format: uuid */
            id: string;
            /** Format: email */
            email: string;
            display_name: string;
            /** @enum {string} */
            role: "admin" | "setter" | "climber";
            /** Format: date-time */
            created_at: string;
        };
        TokenResponse: {
            access_token: string;
            refresh_token: string;
        };
        Gym: {
            /** Format: uuid */
            id: string;
            name: string;
            slug: string;
            /** Format: uuid */
            owner_id: string;
            /** Format: date-time */
            created_at: string;
        };
        GymMember: {
            /** Format: uuid */
            gym_id: string;
            /** Format: uuid */
            user_id: string;
            /** @enum {string} */
            role: "admin" | "setter" | "climber";
        };
        Wall: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            gym_id: string;
            name: string;
            /** Format: date-time */
            created_at: string;
            active_image?: components["schemas"]["WallImage"] | null;
            detection_status?: string | null;
        };
        WallImage: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            wall_id: string;
            storage_key: string;
            /**
             * Format: uri
             * @description Pre-signed URL
             */
            image_url: string;
            is_active: boolean;
            /** Format: date-time */
            created_at: string;
        };
        DetectionJob: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            wall_image_id: string;
            /** @enum {string} */
            status: "pending" | "processing" | "done" | "failed";
            error?: string | null;
            /** Format: date-time */
            created_at: string;
        };
        Hold: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            wall_image_id: string;
            bbox: {
                x: number;
                y: number;
                w: number;
                h: number;
            };
            polygon?: number[][] | null;
            confidence: number;
        };
        Route: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            wall_id: string;
            /** Format: uuid */
            wall_image_id: string;
            /** Format: uuid */
            created_by: string;
            name: string;
            grade?: string | null;
            description?: string | null;
            hold_ids: string[];
            /** Format: date-time */
            created_at: string;
            send_count: number;
            has_sent: boolean;
        };
        Send: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            route_id: string;
            /** Format: uuid */
            user_id: string;
            /** Format: date-time */
            sent_at: string;
            attempts?: number | null;
            notes?: string | null;
        };
        Invite: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            gym_id: string;
            token: string;
            /** @enum {string} */
            role: "admin" | "setter" | "climber";
            /** Format: date-time */
            expires_at: string;
            gym_name?: string;
        };
        RegisterRequest: {
            /** Format: email */
            email: string;
            password: string;
            display_name: string;
        };
        LoginRequest: {
            /** Format: email */
            email: string;
            password: string;
        };
        RefreshRequest: {
            refresh_token: string;
        };
        LogoutRequest: {
            refresh_token: string;
        };
        CreateGymRequest: {
            name: string;
            slug: string;
        };
        InviteMemberRequest: {
            /** Format: email */
            email: string;
            /** @enum {string} */
            role: "admin" | "setter" | "climber";
        };
        CreateWallRequest: {
            name: string;
        };
        UploadImageRequest: {
            /** Format: binary */
            image: string;
        };
        CreateRouteRequest: {
            name: string;
            grade?: string;
            description?: string;
            hold_ids: string[];
        };
        LogSendRequest: {
            attempts?: number;
            notes?: string;
        };
        CreateInviteRequest: {
            /** @enum {string} */
            role?: "admin" | "setter" | "climber";
        };
    };
    responses: {
        /** @description Invalid request */
        BadRequest: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description Missing or invalid authentication */
        Unauthorized: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description Resource not found */
        NotFound: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description Resource already exists */
        Conflict: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
    };
    parameters: {
        GymSlug: string;
        WallId: string;
        RouteId: string;
        InviteToken: string;
    };
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    healthCheck: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Service is healthy */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @example ok */
                        status: string;
                    };
                };
            };
        };
    };
    register: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RegisterRequest"];
            };
        };
        responses: {
            /** @description Account created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TokenResponse"];
                };
            };
            400: components["responses"]["BadRequest"];
            409: components["responses"]["Conflict"];
        };
    };
    login: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginRequest"];
            };
        };
        responses: {
            /** @description Login successful */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TokenResponse"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
        };
    };
    refreshToken: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RefreshRequest"];
            };
        };
        responses: {
            /** @description Token refreshed */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TokenResponse"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
        };
    };
    logout: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LogoutRequest"];
            };
        };
        responses: {
            /** @description Logged out */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
        };
    };
    getMe: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Current user */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["User"];
                };
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    listGyms: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description List of gyms */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Gym"][];
                };
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    createGym: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateGymRequest"];
            };
        };
        responses: {
            /** @description Gym created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Gym"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            409: components["responses"]["Conflict"];
        };
    };
    getGym: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                gymSlug: components["parameters"]["GymSlug"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Gym details */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Gym"];
                };
            };
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
        };
    };
    inviteMember: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                gymSlug: components["parameters"]["GymSlug"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["InviteMemberRequest"];
            };
        };
        responses: {
            /** @description Member invited */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GymMember"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
            409: components["responses"]["Conflict"];
        };
    };
    listWalls: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                gymSlug: components["parameters"]["GymSlug"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description List of walls */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Wall"][];
                };
            };
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
        };
    };
    createWall: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                gymSlug: components["parameters"]["GymSlug"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateWallRequest"];
            };
        };
        responses: {
            /** @description Wall created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Wall"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
        };
    };
    getWall: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                gymSlug: components["parameters"]["GymSlug"];
                wallId: components["parameters"]["WallId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Wall detail */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Wall"];
                };
            };
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
        };
    };
    uploadWallImage: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                gymSlug: components["parameters"]["GymSlug"];
                wallId: components["parameters"]["WallId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["UploadImageRequest"];
            };
        };
        responses: {
            /** @description Image uploaded */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WallImage"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
        };
    };
    listHolds: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                gymSlug: components["parameters"]["GymSlug"];
                wallId: components["parameters"]["WallId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description List of holds */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Hold"][];
                };
            };
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
        };
    };
    listRoutes: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                gymSlug: components["parameters"]["GymSlug"];
                wallId: components["parameters"]["WallId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description List of routes */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Route"][];
                };
            };
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
        };
    };
    createRoute: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                gymSlug: components["parameters"]["GymSlug"];
                wallId: components["parameters"]["WallId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateRouteRequest"];
            };
        };
        responses: {
            /** @description Route created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Route"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
        };
    };
    getRoute: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                gymSlug: components["parameters"]["GymSlug"];
                wallId: components["parameters"]["WallId"];
                routeId: components["parameters"]["RouteId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Route detail */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Route"];
                };
            };
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
        };
    };
    deleteRoute: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                gymSlug: components["parameters"]["GymSlug"];
                wallId: components["parameters"]["WallId"];
                routeId: components["parameters"]["RouteId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Route deleted */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
        };
    };
    logSend: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                gymSlug: components["parameters"]["GymSlug"];
                wallId: components["parameters"]["WallId"];
                routeId: components["parameters"]["RouteId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LogSendRequest"];
            };
        };
        responses: {
            /** @description Send logged */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Send"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
            409: components["responses"]["Conflict"];
        };
    };
    removeMySend: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                gymSlug: components["parameters"]["GymSlug"];
                wallId: components["parameters"]["WallId"];
                routeId: components["parameters"]["RouteId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Send removed */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
        };
    };
    getMyLogbook: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description List of sends */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Send"][];
                };
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    createInvite: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                gymSlug: components["parameters"]["GymSlug"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateInviteRequest"];
            };
        };
        responses: {
            /** @description Invite created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Invite"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
        };
    };
    validateInvite: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                token: components["parameters"]["InviteToken"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Invite details */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Invite"];
                };
            };
            404: components["responses"]["NotFound"];
        };
    };
    acceptInvite: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                token: components["parameters"]["InviteToken"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Invite accepted */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GymMember"];
                };
            };
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
            409: components["responses"]["Conflict"];
        };
    };
}
